"""Add column_profiles table

Revision ID: 185da8226d61
Revises: a156654a529b
Create Date: 2025-09-07 02:22:02.166751

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
import pgvector.sqlalchemy

revision = '185da8226d61'
down_revision = 'a156654a529b'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('column_profiles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('database_name', sa.String(length=255), nullable=False),
    sa.Column('table_name', sa.String(length=255), nullable=False),
    sa.Column('column_name', sa.String(length=255), nullable=False),
    sa.Column('data_type', sa.String(length=100), nullable=False),
    sa.Column('table_row_count', sa.Integer(), nullable=False),
    sa.Column('null_count', sa.Integer(), nullable=False),
    sa.Column('non_null_count', sa.Integer(), nullable=False),
    sa.Column('distinct_count', sa.Numeric(), nullable=True),
    sa.Column('min_value', sa.Text(), nullable=True),
    sa.Column('max_value', sa.Text(), nullable=True),
    sa.Column('length_min', sa.Integer(), nullable=True),
    sa.Column('length_max', sa.Integer(), nullable=True),
    sa.Column('char_classes', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('common_prefixes', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('top_k_values', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('distinct_sample', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('minhash_signature', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('english_description', sa.Text(), nullable=True),
    sa.Column('short_summary', sa.Text(), nullable=True),
    sa.Column('long_summary', sa.Text(), nullable=True),
    sa.Column('vector_embedding', pgvector.sqlalchemy.vector.VECTOR(dim=1536), nullable=True),
    sa.Column('generated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('database_name', 'table_name', 'column_name', name='unique_column_profile')
    )
    op.create_index(op.f('ix_column_profiles_id'), 'column_profiles', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_column_profiles_id'), table_name='column_profiles')
    op.drop_table('column_profiles')
    # ### end Alembic commands ###