"""add_document_review_fields

Revision ID: 4fd493ac8564
Revises: ca2e85ebc2a4
Create Date: 2025-08-17 21:09:22.681756

"""
from alembic import op
import sqlalchemy as sa


revision = '4fd493ac8564'
down_revision = 'ca2e85ebc2a4'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('documents', sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('documents', sa.Column('reviewed_by', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'documents', 'users', ['reviewed_by'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'documents', type_='foreignkey')
    op.drop_column('documents', 'reviewed_by')
    op.drop_column('documents', 'reviewed_at')
    # ### end Alembic commands ###