"""Add Document model with UUID and enums

Revision ID: 6485d8e0c189
Revises: 1249fdc57a30
Create Date: 2025-07-27 05:13:58.990902

"""
from alembic import op
import sqlalchemy as sa


revision = '6485d8e0c189'
down_revision = '1249fdc57a30'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Drop the old table and recreate with new structure
    op.drop_table('documents')
    
    # Create the documents table with new structure
    op.create_table('documents',
        sa.Column('id', sa.UUID(), nullable=False),
        sa.Column('user_id', sa.Integer(), nullable=False),
        sa.Column('business_id', sa.Integer(), nullable=False),
        sa.Column('filename', sa.String(), nullable=False),
        sa.Column('file_url', sa.String(), nullable=False),
        sa.Column('file_type', sa.Enum('PDF', 'JPG', 'PNG', name='filetype'), nullable=False),
        sa.Column('document_type', sa.Enum('INVOICE', 'RECEIPT', name='documenttype'), nullable=False),
        sa.Column('status', sa.Enum('PENDING', 'PROCESSING', 'COMPLETED', 'FAILED', name='documentstatus'), nullable=False),
        sa.Column('confidence_score', sa.Float(), nullable=True),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
        sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], ),
        sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_documents_id'), 'documents', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('documents', sa.Column('content', sa.TEXT(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'documents', type_='foreignkey')
    op.alter_column('documents', 'id',
               existing_type=sa.UUID(),
               type_=sa.INTEGER(),
               existing_nullable=False)
    op.drop_column('documents', 'confidence_score')
    op.drop_column('documents', 'status')
    op.drop_column('documents', 'document_type')
    op.drop_column('documents', 'file_type')
    op.drop_column('documents', 'file_url')
    op.drop_column('documents', 'business_id')
    # ### end Alembic commands ###