"""enable pgvector extension

Revision ID: 90a76db1c2da
Revises: 185da8226d61
Create Date: 2025-09-16 20:39:04.300929

"""
from alembic import op
import sqlalchemy as sa


revision = '90a76db1c2da'
down_revision = '185da8226d61'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Enable pgvector extension for VECTOR columns
    op.execute('CREATE EXTENSION IF NOT EXISTS "vector"')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Note: We don't drop the extension in downgrade to avoid breaking other applications
    # that might be using it. Extensions are typically left in place.
    pass
    # ### end Alembic commands ###