"""Add FieldCorrection model for tracking field corrections

Revision ID: ca2e85ebc2a4
Revises: 5128a1c50cb4
Create Date: 2025-08-10 04:34:42.980279

"""
from alembic import op
import sqlalchemy as sa


revision = 'ca2e85ebc2a4'
down_revision = '5128a1c50cb4'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('field_corrections',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('document_id', sa.UUID(), nullable=False),
    sa.Column('field_name', sa.String(), nullable=False),
    sa.Column('original_value', sa.Text(), nullable=True),
    sa.Column('corrected_value', sa.Text(), nullable=False),
    sa.Column('corrected_by', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['corrected_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_field_corrections_document_id'), 'field_corrections', ['document_id'], unique=False)
    op.create_index(op.f('ix_field_corrections_field_name'), 'field_corrections', ['field_name'], unique=False)
    op.create_index(op.f('ix_field_corrections_id'), 'field_corrections', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_field_corrections_id'), table_name='field_corrections')
    op.drop_index(op.f('ix_field_corrections_field_name'), table_name='field_corrections')
    op.drop_index(op.f('ix_field_corrections_document_id'), table_name='field_corrections')
    op.drop_table('field_corrections')
    # ### end Alembic commands ###